

[package]
name = "libfranka"
version = "0.1.0"


[workspace]
name = "libfranka"
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package.build-dependencies]
cmake = "*"
make = "*"
ninja = "*"

[package.host-dependencies]
eigen = "*"
poco = "*"
fmt = "==12.1.0" 
urdfdom = "5.1.*"
pinocchio = "*"

[package.run-dependencies]

[package.build]
backend = { name = "pixi-build-cmake" , version = "*"}

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release", "-DBUILD_TESTS=OFF", "-DBUILD_EXAMPLES=OFF", "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"]
